name: npm-publish-alpha

on:
  push:
    branches:
      - '*-alpha.*'

jobs:
  npm-publish:
    if: contains(github.event.head_commit.message, 'publish')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_SECRET }}
          tag: alpha
