name: npm-publish

on:
  push:
    branches:
      - '*-alpha.*'

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    outputs:
      trigger_next: ${{ steps.set_output.outputs.trigger_next }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check commit message
        id: check_commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          echo "TRIGGER_NEXT=false" >> $GITHUB_ENV
          if [[ "$commit_message" == *"specific-string"* ]]; then
            echo "TRIGGER_NEXT=true" >> $GITHUB_ENV
          fi
      - name: Set output
        id: set_output
        run: echo "::set-output name=trigger_next::$TRIGGER_NEXT"

  npm-publish:
    needs: check_commit_message
    if: needs.check_commit_message.outputs.trigger_next == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: test
        run: npm test

      - name: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_SECRET }}
          tag: alpha
